### ISSUE TITLE
Some strings could not be translated

### ISSUE THREAD

**Issue by Jennifer88huang** [streamnative/translation-guidelines#13]
**Describe the bug**
When I translate "client-libraries-websocket" file at https://crowdin.com/translate/apache-pulsar/18/en-zhcn, some strings are locked, the error msg is "This string is marked as duplicate and should not be translated."

**Expected behavior**
It should be translated.

**Screenshots**
![image](https://user-images.githubusercontent.com/47805623/61194070-d73dee00-a6f1-11e9-9555-08b9f8d01baf.png)

**Additional context**
I've encountered more in this file.

**Comment by Jennifer88huang** [comment]
@Ssssssusan Francis encounters such issues while translating, could you please help resolve this issue for him?

**Comment by francis-du** [comment]
@Ssssssusan Hi ,I found this problem during translation, how can I solve it?

**Comment by Jennifer88huang** [comment]
@francis-du Thank you very much for your question. It is by design. Since there are duplicate string, we just need to translate one place, and other duplication will adopt the same translation. It is to avoid different translation version for the same string.
